# ========================
# 模板路径
# ========================
indexHtml=../index.html
bookmarkHtml=../src/tpl/bookmark.html
sideHtml=../src/tpl/side.html
templateHtml=../src/tpl/new.html


# ========================
# HTML 扫描, 文件排除（用 | 分隔, 支持具体文件名与正则表达式混合, 不带.html后缀）
# ========================
htmlDir=../html
exclude=.*_


# ========================
# 媒体扫描, 子目录排除（用 | 分隔）
# ========================
galleryDir=../gallery
videoDir=../video
audioDir=../audio
ebookDir=../ebook
galleryDirExcludeDirs=img|xx
videoDirExcludeDirs=
audioDirExcludeDirs=
ebookDirExcludeDirs=


# ========================
# 切片输出, 大小限制
# ========================
dataDir=../src/js/data
sliceSize=300


# ========================
# WebP
# ========================
cwebpPath=libwebp/bin/cwebp.exe
imgInputDir=D:/_temp/screenshot/
imgResizedOutputDir=D:/_temp/screenshot/resized/
webpOutputDir=../gallery/img/
webpOutputDir2=D:/_temp/screenshot/t


# ========================
# Java
# ========================
jre_path=D:/shared/jdk/temurin-1.8/bin/javaw


# ========================
# vscode
# ========================
vscode_path=C:/Users/diff/AppData/Local/Programs/Microsoft VS Code/Code.exe


# ========================
# 虚拟服务器
# ========================
static-web-server_path=server/static-web-server.exe
port=8000
log_level=error
root_path=../


# ========================
# takeout_keep
# ========================
keep_takeout_zip_folder=D:/_temp/keep_takeout
webpQuality=80
imgMaxWidth=800


# ========================
# github
# ========================
github_page=diff4x.github.io


# ========================
# giscus
# ========================
data-repo=diff4x/comments
data-repo-id=R_kgDOSlizXw
data-category-id=DIC_kwDOSlizX84C9qT-
cmt_mapper=../src/cmt_mapper.json


# ========================
# esbuild
# ========================
esbuild_path=esbuild/esbuild.exe
js_input_dir=../src/js/raw
js_output_dir=../src/js
css_input_dir=../src/css/raw
css_output_dir=../src/css


# ========================
# VPNHeartbeatTray
# ========================
URL_TO_CHECK=https://www.google.com


# ========================
# PWA 后台更新探测频率 (毫秒)
# ========================
update_interval=10000
update_interval_local=2000


# ========================
# Service Worker 强缓存名单, 只要经过冷启即可离线使用
# ========================
coreFiles=\
    /| \
    /index.html| \
    /src/tpl/bookmark.html| \
    /src/tpl/epub.html| \
    /src/tpl/pano.html| \
    /src/tpl/pdf.html| \
    /src/tpl/side.html| \
    /src/tpl/txn_parser.html| \
    /src/tpl/txt.html| \
    /src/tpl/go.html| \
    /src/tpl/street_view_uploader.html| \
    /src/css/index.css| \
    /src/css/font.css| \
    /src/css/bookmark.css| \
    /src/css/side.css| \
    /src/css/content.css| \
    /src/css/bilingual.css| \
    /src/js/index.js| \
    /src/js/bookmark.js| \
    /src/js/side.js| \
    /src/js/content.js| \
    /src/js/worker.js| \
    /src/js/encoding.min.js| \
    /src/js/bilingual.js| \
    /src/js/pinyinData.js| \
    /src/js/txn_parser.js| \
    /src/cmt_mapper.json| \
    /src/third/bibi/and/jo.js| \
    /src/third/bibi/extensions/analytics.js| \
    /src/third/bibi/extensions/epubcfi.js| \
    /src/third/bibi/extensions/sanitizer.js| \
    /src/third/bibi/extensions/unaccessibilizer.js| \
    /src/third/bibi/extensions/zine.js| \
    /src/third/bibi/extensions/extractor/at-once.js| \
    /src/third/bibi/extensions/extractor/on-the-fly.bibi-zip-loader.worker.alt.js| \
    /src/third/bibi/extensions/extractor/on-the-fly.bibi-zip-loader.worker.js| \
    /src/third/bibi/extensions/extractor/on-the-fly.js| \
    /src/third/bibi/presets/default.js| \
    /src/third/bibi/resources/scripts/bibi.js| \
    /src/third/bibi/resources/scripts/polyfills/bundle.js| \
    /src/third/bibi/resources/scripts/polyfills/encoding.js| \
    /src/third/bibi/resources/scripts/polyfills/intersection-observer.js| \
    /src/third/bibi/resources/styles/bibi.css| \
    /src/third/bibi/wardrobe/everyday/bibi.dress.css| \
    /src/third/pdfjs/build/pdf.js| \
    /src/third/pdfjs/build/pdf.worker.js| \
    /src/third/pdfjs/web/debugger.js| \
    /src/third/pdfjs/web/viewer.css| \
    /src/third/pdfjs/web/viewer.js| \
    /src/third/pdfjs/web/locale/locale.properties| \
    /src/third/pdfjs/web/locale/en-US/viewer.properties| \
    /src/third/photo-sphere-viewer/photo-sphere-viewer.min.js| \
    /src/third/photo-sphere-viewer/three.min.js| \
    /src/third/prism/prism.css| \
    /src/third/prism/prism.js| \

    /src/css/bilingual.css| \
    /src/js/bilingual.js| \
    /src/wasm/compute_intensive_task_processor.min.js| \
    /src/wasm/compute_intensive_task_processor_bg.wasm
